#Requires -Version 5.1
<#
.SYNOPSIS
    Builds MsixModernContextMenuHandler.dll with VS Build Tools 2022 (Release|x64).

.PARAMETER Configuration
    Build configuration. Default: Release.

.PARAMETER Clean
    Run a clean build (msbuild /t:Clean,Build).
#>
param(
    [ValidateSet('Release', 'Debug')]
    [string] $Configuration = 'Release',

    [switch] $Clean
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Locate MSBuild via vswhere
# ---------------------------------------------------------------------------

$vswhere = Join-Path ${env:ProgramFiles(x86)} `
           'Microsoft Visual Studio\Installer\vswhere.exe'

if (-not (Test-Path $vswhere)) {
    Write-Error "vswhere.exe not found at: $vswhere`nMake sure VS Build Tools 2022 are installed."
    exit 1
}

$msbuildPath = & $vswhere `
    -latest `
    -products '*' `
    -requires Microsoft.Component.MSBuild `
    -find 'MSBuild\**\Bin\MSBuild.exe' |
    Select-Object -First 1

if (-not $msbuildPath -or -not (Test-Path $msbuildPath)) {
    Write-Error "MSBuild.exe not found. Install the 'MSBuild' component in VS Build Tools 2022."
    exit 1
}

Write-Verbose "MSBuild: $msbuildPath"

# ---------------------------------------------------------------------------
# Version -- increment patch, regenerate src\version.rc
# ---------------------------------------------------------------------------

$versionFile = Join-Path $PSScriptRoot 'version.txt'
$versionRc   = Join-Path $PSScriptRoot 'src\version.rc'

$raw   = (Get-Content $versionFile -Raw).Trim()
$parts = $raw -split '\.'
if ($parts.Count -lt 3) { $parts = @('0', '9', '0') }

$major = [int]$parts[0]
$minor = [int]$parts[1]
$patch = [int]$parts[2] + 1

$version     = "$($major).$($minor).$($patch)"
$versionFull = "$($major).$($minor).$($patch).0"
$versionRes  = "$($major),$($minor),$($patch),0"

Set-Content -Path $versionFile -Value $version -Encoding UTF8
Write-Output "Version: $versionFull"

$rcContent = @"
// Generated by Build-ModernContextMenuHandler.ps1 -- do not edit manually.
#include <windows.h>

VS_VERSION_INFO VERSIONINFO
 FILEVERSION $versionRes
 PRODUCTVERSION $versionRes
 FILEFLAGSMASK 0x3fL
#ifdef _DEBUG
 FILEFLAGS 0x1L
#else
 FILEFLAGS 0x0L
#endif
 FILEOS 0x40004L
 FILETYPE 0x2L
 FILESUBTYPE 0x0L
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904b0"
        BEGIN
            VALUE "CompanyName",      "MSIXForcelets"
            VALUE "FileDescription",  "MSIX Modern Context Menu Handler (IExplorerCommand)"
            VALUE "FileVersion",      "$versionFull"
            VALUE "InternalName",     "MsixModernContextMenuHandler"
            VALUE "LegalCopyright",   "Copyright 2026 Andreas Nick"
            VALUE "OriginalFilename", "MsixModernContextMenuHandler.dll"
            VALUE "ProductName",      "MsixModernContextMenuHandler"
            VALUE "ProductVersion",   "$versionFull"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
END
"@

[IO.File]::WriteAllText($versionRc, $rcContent, [Text.Encoding]::UTF8)

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

$sln    = Join-Path $PSScriptRoot 'MsixModernContextMenuHandler.sln'
$target = if ($Clean) { 'Clean;Build' } else { 'Build' }

$msbuildArgs = @(
    $sln
    "/t:$target"
    "/p:Configuration=$Configuration"
    '/p:Platform=x64'
    '/nologo'
    '/verbosity:minimal'
)

Write-Output "Building $Configuration|x64 ..."
& $msbuildPath @msbuildArgs

if ($LASTEXITCODE -ne 0) {
    Write-Error "Build failed (exit $LASTEXITCODE)."
    exit $LASTEXITCODE
}

$dll     = Join-Path $PSScriptRoot "bin\$Configuration\MsixModernContextMenuHandler.dll"
$testDir = Join-Path $PSScriptRoot 'Test'

if (-not (Test-Path $dll)) {
    Write-Warning "MSBuild reported success but DLL not found at: $dll"
    exit 1
}

Write-Output "Build succeeded. Version: $versionFull"
Write-Output "Output: $dll"

# ---------------------------------------------------------------------------
# Copy DLL to Test\ so Install-ModernContextMenuHandler.ps1 finds it there
# ---------------------------------------------------------------------------

Copy-Item -Path $dll -Destination $testDir -Force
Write-Output "Copied DLL to: $testDir"

Write-Output ""
Write-Output "Next steps for outside-MSIX testing:"
Write-Output "  1. Adjust Test\MsixModernContextMenuHandler.json (executable path etc.)"
Write-Output "  2. Run Test\Install-ModernContextMenuHandler.ps1 [-RestartExplorer]"
